config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get "logout"           => "sessions#destroy", :as => "logout"
  get "login"            => "sessions#new", :as => "login"
  get "signup"           => "users#new", :as => "signup"
  get "terms"            => "home#terms", :as => "terms"
  get "pricing"          => "charges#new", :as => "pricing"
  get "schedule"         => "courses#index", :as => "schedule"
  get "contact"          => "contact_us/contacts#new", :as => "contact"
  get "profile"          => "profiles#index", :as => "profile"
  get "profile/edit"     => "profiles#edit", :as => "edit_profile"
  patch "profile/update" => "profiles#update", :as => "update_profile"
  post 'users'           => "users#create"

  resources :courses do
    resources :exams
  end

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions
  resources :charges
  resources :password_resets

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_login
  before_action :find_profile
  
  def index
  end

  def edit
  end

  def show
  end
  
  def update
    if @profile.update profile_params
      flash[:success] = "Profile was successfully updated."
      redirect_to profile_url
    else
      render 'edit'
    end
  end

  def destroy
    current_user.delete
  end

  private
    def find_profile
      @profile = current_user
    end
  
    def profile_params
      params.require(:user).permit(:first_name, :last_name, :address_one, :address_two, :city, :state, :zip_code, :school_name)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end

  def supported_schools
    [
      ['University of Houston - Main Campus', 'University of Houston - Main Campus'],
      ['University of Houston - Clear Lake', 'University of Houston - Clear Lake'],
      ['Houston Community College', 'Houston Community College'],
      ['Lone Star College', 'Lone Star College'],
      ['San Jacinto College', 'San Jacinto College']
    ]
  end
end

app/views/profiles/edit.html.erb
<header class="wrap-title">
  <div class="container">
    <h1 class="page-title"><%= title 'Edit Profile' %></h1>
    <% description 'Edit Profile page.' %>
    <% keywords 'edit profile page' %>
  </div>
</header>
<%= bootstrap_form_for @profile, url: update_profile_path do |f| %>
	<% if @profile.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @profile.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="container">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<%= f.text_field :first_name, label: "First Name" %>
			<%= f.text_field :last_name, label: "Last Name" %>
			<%= f.text_field :address_one, label: "Address 1" %>
			<%= f.text_field :address_two, label: "Address 2" %>
			<%= f.text_field :city, label: "City" %>
			<%= f.select :state, options_for_select(us_states), label: "State" %>
			<%= f.phone_field :zip_code, label: "Zip Code" %>
			<%= f.select :school_name, options_for_select(supported_schools), label: "School" %>
			<%= f.submit %>
			<h4><%= link_to 'Back', profile_url %></h4>
		</div>
		<div class="col-md-4">
		</div>
	</div>
<% end %>
<script type="text/javascript">
    mixpanel.track("Edited Profile");
</script>

app/views/profiles/index.html.erb
<header class="wrap-title">
  <div class="container">
    <h1 class="page-title"><%= title 'My Profile' %></h1>
    <% description 'My Profile page.' %>
    <% keywords 'my profile page view' %>
  </div>
</header>

<br>
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <div class="table-responsive">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td><strong>First Name</strong></td>
            <td><%= current_user.first_name %></td>
          </tr>
          <tr>
            <td><strong>Last Name</strong></td>
            <td><%= current_user.last_name %></td>
          </tr>
          <tr>
            <td><strong>Mailing Address</strong></td>
            
            <td><% if current_user.city? %>
                  <%= current_user.address_one %> <%= current_user.address_two %><br><%= current_user.city %>,&nbsp;<%= current_user.state %>&nbsp;<%= current_user.zip_code %>
                <% end %>
            </td>
          </tr>
          <tr>
            <td><strong>School</strong></td>
            <td><%= current_user.school_name %></td>
          </tr>
        </tbody>
      </table>
      <h4><%= button_to "Edit Profile", edit_profile_path(current_user.id), :class => "btn btn-default", :method => :get %></h4>
    </div>
    <% if current_user.customer_id? %>
      <h4><%= button_to "Cancel Your Subscription", charge_path(current_user.id), :class => "btn btn-default", :method => :delete, data: { confirm: 'Are you sure?' } %></h4>
    <% end %>
  </div>
</div>

app/views/profiles/show.html.erb
<header class="wrap-title">
  <div class="container">
    <h1 class="page-title"><%= title 'Edit Profile' %></h1>
    <% description 'Edit Profile page.' %>
    <% keywords 'edit profile page' %>
  </div>
</header>
<%= bootstrap_form_for @profile do |f| %>
	<% if @profile.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @profile.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="container">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.text_field :first_name, label: "First Name" %>
			<%= f.text_field :last_name, label: "Last Name" %>
			<%= f.text_field :address_one, label: "Address 1" %>
			<%= f.text_field :address_two, label: "Address 2" %>
			<%= f.text_field :city, label: "City" %>
			<%= f.text_field :state, label: "State" %>
			<%= f.text_field :zip_code, label: "Zip Code" %>
			<%= f.text_field :school_name, label: "School" %>
			<%= f.submit %>
			<h4><%= link_to 'Back', profile_url %></h4>
		</div>
		<div class="col-md-4">
		</div>
	</div>
<% end %>