config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get "logout"           => "sessions#destroy", :as => "logout"
  get "login"            => "sessions#new", :as => "login"
  get "signup"           => "users#new", :as => "signup"
  get "terms"            => "home#terms", :as => "terms"
  get "pricing"          => "charges#new", :as => "pricing"
  get "schedule"         => "courses#index", :as => "schedule"
  get "contact"          => "contact_us/contacts#new", :as => "contact"
  get "profile"          => "profiles#index", :as => "profile"
  get "profile/edit"     => "profiles#edit", :as => "edit_profile"
  patch "profile/update" => "profiles#update", :as => "update_profile"
  post 'users'           => "users#create"

  resources :courses do
    resources :exams
  end

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions
  resources :charges
  resources :password_resets

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	skip_before_filter :require_login

  def create
  	@user = User.find_by_email(params[:email])
  	@user.deliver_reset_password_instructions! if @user
    flash[:success] = "Instructions have been sent to your email."
  	redirect_to root_path
  end

  def edit
  	@user = User.load_from_reset_password_token(params[:id])
  	@token = params[:id]
  	not_authenticated if !@user
  end

  def update
  	@token = params[:token]
  	@user = User.load_from_reset_password_token(params[:token])
  	not_authenticated if !@user
  	@user.password_confirmation = params[:user][:password_confirmation]

  	if @user.change_password!(params[:user][:password])
      flash[:success] = "Password was successfully updated."
  		redirect_to login_url
  	else
  		render :action => 'edit'
  	end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<header class="wrap-title">
  <div class="container">
    <h1 class="page-title"><%= title 'Reset Password' %></h1>
    <% description 'Reset Password page.' %>
    <% keywords 'reset password page' %>
  </div>
</header>
<div class="container">
<div class="col-md-4">
</div>
<div class="col-md-4">
<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put}, :role => :form do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% @user.email %>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, label: "Password", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, label: "Confirm Password", class: "form-control" %>
  </div>
  <%= hidden_field_tag :token, @token %>
  <%= f.submit 'Save' class: "btn btn-f2yd" %>
<% end %>
</div>
<div class="col-md-4">
</div>
</div>

app/views/password_resets/new.html.erb
<header class="wrap-title">
  <div class="container">
    <h1 class="page-title"><%= title 'Password Reset' %></h1>
    <% description 'Password Reset page.' %>
    <% keywords 'password reset page' %>
  </div>
</header>
<div class="container">
  <div class="col-md-4">
    <%= form_tag password_resets_path, :method => :post do %>
      <div class="field">
        <%= label_tag :email %><br />
        <%= text_field_tag :email, params[:email] %>
        <%= submit_tag "Reset Password" %>
      </div>
    <% end %>
    <br>
    <%= link_to 'Back', login_path %>
  </div>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>