config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get "logout"           => "sessions#destroy", :as => "logout"
  get "login"            => "sessions#new", :as => "login"
  get "signup"           => "users#new", :as => "signup"
  get "terms"            => "home#terms", :as => "terms"
  get "pricing"          => "charges#new", :as => "pricing"
  get "schedule"         => "courses#index", :as => "schedule"
  get "contact"          => "contact_us/contacts#new", :as => "contact"
  get "profile"          => "profiles#index", :as => "profile"
  get "profile/edit"     => "profiles#edit", :as => "edit_profile"
  patch "profile/update" => "profiles#update", :as => "update_profile"
  post 'users'           => "users#create"

  resources :courses do
    resources :exams
  end

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions
  resources :charges
  resources :password_resets

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	before_filter :require_login, :only => :create

	def new
	end

	def create
		# Amount in cents
		@amount = 0
		# Used for payment confirmation page
		@dollar_amount = (399 / 100.0)

		customer = Stripe::Customer.create(
			:email 	=> current_user.email,
			:card 	=> params[:stripeToken],
			:plan => 'f2yd-4'
		)

		current_user.customer_id = customer.id
		current_user.save!
	
	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to charges_path
	end

	def destroy
		Stripe.api_key = ENV['SECRET_KEY']
		customer = Stripe::Customer.retrieve(current_user.customer_id)
		customer.delete

		current_user.customer_id = ""
		current_user.save!
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="container">
	<h2 class="animated fadeInDownBig">
		Thanks, you paid <strong>$<%= @dollar_amount %></strong>! Your monthly subscription is now active.
	</h2>
</div>
<script type="text/javascript">
    mixpanel.track("Subscribed");
</script>

app/views/charges/destroy.html.erb
<div class="container">
  <h2 class="animated fadeInDownBig">Your subscription has been canceled.</h2>
</div>
<script type="text/javascript">
    mixpanel.track("Canceled Subscription");
</script>

app/views/charges/new.html.erb
<header class="wrap-title">
  <div class="container">
    <h1 class="page-title"><%= title 'Pricing' %></h1>
    <% description 'Pricing page.' %>
    <% keywords 'pricing page' %>
  </div>
</header>
<div class="container">
  <section>
    <div class="row">
      <div class="col-md-2 col-sm-2">
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="active-pricing-box animated fadeInUp animation-delay-6">
          <div class="active-pricing-box-price">
            <h2>Free to Sign Up</h2>
          </div>
          <div class="active-pricing-box-content">
            <ul>
              <li><i class="fa fa-check-square-o"></i> <span>Sign Up.</span></li>
              <li><i class="fa fa-calendar"></i> <span>Input your schedule.</span></li>
              <li><i class="fa fa-pencil"></i> <span>Add exams and proper forms.</span></li>
            </ul>
          </div>
          <div class="active-pricing-box-footer">
            <% if current_user %>
              <%= button_to "Submit Your Schedule", schedule_path, :class => "btn btn-f2yd", :method => :get %>
            <% else %>
              <%= button_to "Sign Up", signup_path, :class => "btn btn-f2yd", :method => :get %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="active-pricing-box animated fadeInUp animation-delay-7">
          <div class="active-pricing-box-price">
            <h2>$3.99<span id="month_text">/mo</span></h2>
          </div>
          <div class="active-pricing-box-content">
            <ul>
              <li><i class="fa fa-truck"></i><span>Forms arrive one week prior to exams.</span></li>
              <li><i class="fa fa-check-square"></i> <span>One spare form per exam.</span></li>
              <li><i class="fa fa-pencil"></i> <span>#2 pencil included with each delivery.</span></li>
            </ul>
          </div>
          <div class="active-pricing-box-footer">
            <% if current_user %>
              <% if current_user.city? %>
                <%= form_tag charges_path do %>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-name="Forms to Your Door"
                data-email="<%= current_user.email %>"
                data-description="$3.99/month"
                data-amount="199"
                data-panel-label="Pay {{amount}}">
                </script>
                <% end %>
              <% else %>
                <%= button_to "Complete Your Profile", edit_profile_path, :class => "btn btn-f2yd", :method => :get %>
              <% end %>
            <% else %>
              <%= button_to "Log In to Purchase", login_path, :class => "btn btn-f2yd", :method => :get %>
            <% end %>
          </div>
        </div>
        <div class="col-md-2 col-sm-2">
        </div>
      </div>
    </div>
  </section>
</div>
<script type="text/javascript">
    mixpanel.track("Viewed Pricing");
</script>