config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  get "logout"           => "sessions#destroy", :as => "logout"
  get "login"            => "sessions#new", :as => "login"
  get "signup"           => "users#new", :as => "signup"
  get "terms"            => "home#terms", :as => "terms"
  get "pricing"          => "charges#new", :as => "pricing"
  get "schedule"         => "courses#index", :as => "schedule"
  get "contact"          => "contact_us/contacts#new", :as => "contact"
  get "profile"          => "profiles#index", :as => "profile"
  get "profile/edit"     => "profiles#edit", :as => "edit_profile"
  patch "profile/update" => "profiles#update", :as => "update_profile"
  post 'users'           => "users#create"

  resources :courses do
    resources :exams
  end

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions
  resources :charges
  resources :password_resets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <meta name="description" content="Scantrons and other forms delivered to you right before each test, hassle-free.">
	  <meta name="keywords" content="scantron,delivery,blue,book,form,exam,test,midterm,final,college,university,forms,school,education">
		<%= display_meta_tags :site => 'Forms to Your Door' %>
		<% description 'Scantrons and other forms delivered to you right before each test, hassle-free.' %>
		<% keywords 'scantron delivery blue book form exam test midterm final college university forms school education deliver' %>
	  <%= favicon_link_tag "f2yd/favicon.ico" %>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-57573049-1', 'auto');
			ga('send', 'pageview');
		</script>
		<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
		for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
		mixpanel.init("7072b2fe4fbf5788c9ad1bbd79ef938f");</script><!-- end Mixpanel -->
	</head>
	<body>
		<div class="boxed animated fadeIn animation-delay-5">
			<!--<header id="header" class="hidden-xs">
	      <div class="container">
	        <div id="header-title">
	          <h1 class="animated fadeInDown"><a href="/">Forms to <span>Your</span> Door</a></h1>
	          <p class="animated fadeInLeft">All your exam supplies, from our door to yours.</p>
	        </div>
	      </div>
	    </header>-->
	    <nav class="navbar navbar-static-top navbar-mind" role="navigation">
	      <div class="container">
					<div class="navbar-header">
						<a class="navbar-brand hidden-xs" href="/">Forms to <span>Your </span>Door</a>
					</div>
	        <div class="navbar-header">
	          <a class="navbar-brand visible-xs" href="/">Forms to <span>Your </span>Door</a>
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-mind-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <i class="fa fa-bars fa-inverse"></i>
	          </button>
	        </div>
					<div class="collapse navbar-collapse navbar-mind-collapse">
						<ul class="nav navbar-nav">
							<li>
								<a href="/">Home</a>
							</li>
							<% if current_user %>
							<li>
								<%= link_to "My Schedule", schedule_path %>
							</li>
							<li>
								<%= link_to "My Profile", profile_path %>
							</li>
							<% end %>
							<li>
								<%= link_to "Pricing", pricing_path %>
							</li>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<% if current_user %>
								<% if current_user.first_name.empty? or current_user.last_name.empty? %>
									<li><%= link_to "Logged in as " + current_user.email, profile_path %></li>
								<% else %>
									<li><%= link_to "Logged in as " + current_user.first_name + " " + current_user.last_name, profile_path %></li>
								<% end %>
								<li><%= link_to "Log out", logout_path %></li>
							<% else %>
								<li><%= link_to "Sign up", signup_path %></li>
								<li><%= link_to "Log in", login_path %></li>
							<% end %>
						</ul>
					</div>
	      </div>
	    </nav>
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert alert-#{name}" %>
			<% end %>
			<%= yield %>
	      <aside id="footer-widgets">
	        <div class="container">
	          <div class="row">
	            <h1></h1>
	          </div>
	          <div class="row">
	            <div class="col-md-1">
	            </div>
	            <div class="col-md-10" id="footer-links">
                <a href="/">Home</a> |
									<% if current_user %>
	                  <%= link_to "My Schedule", schedule_path %> |
	                  <%= link_to "My Profile", profile_path %> |
	                <% end %>
	                <%= link_to "Pricing", pricing_path %> |
	                <%= link_to "Contact", contact_path %> |
									<%= link_to "Terms & Conditions", terms_path %> |
									<% if current_user %>
										<% if current_user.first_name.empty? or current_user.last_name.empty? %>
											<%= link_to "Logged in as " + current_user.email, profile_path %> |
										<% else %>
											<%= link_to "Logged in as " + current_user.first_name + " " + current_user.last_name, profile_path %> |
										<% end %>
										<%= link_to "Log out", logout_path %>
									<% else %>
										<%= link_to "Sign up", signup_path %> |
										<%= link_to "Log in", login_path %>
									<% end %>
	            </div>
	            <div class="col-md-1">
	            </div>
	          </div>
	        </div>
	      </aside>
	      <footer id="footer">
	        <p>&copy; <script type="text/javascript">
  document.write(new Date().getFullYear());
</script> Forms to Your Door, LLC | All rights reserved.</p>
	      </footer>
		</div>
		<script type="text/javascript">
		  var FHChat = {product_id: "3e51b437d9a3"};
		  FHChat.properties={};FHChat.set=function(key,data){this.properties[key]=data};!function(){var a,b;return b=document.createElement("script"),a=document.getElementsByTagName("script")[0],b.src="https://chat-client-js.firehoseapp.com/chat-min.js",b.async=!0,a.parentNode.insertBefore(b,a)}();
		</script>
	</body>
</html>